return {
    { "Plus Sign", "+" },
    { "Less-Than Sign", "<" },
    { "Equals Sign", "=" },
    { "Greater-Than Sign", ">" },
    { "Vertical Line", "|" },
    { "Tilde", "~" },
    { "Not Sign", "¬" },
    { "Plus-Minus Sign", "±" },
    { "Multiplication Sign", "×" },
    { "Division Sign", "÷" },
    { "Greek Reversed Lunate Epsilon Symbol", "϶" },
    { "Arabic-Indic Cube Root", "؆" },
    { "Arabic-Indic Fourth Root", "؇" },
    { "Arabic Ray", "؈" },
    { "Fraction Slash", "⁄" },
    { "Commercial Minus Sign", "⁒" },
    { "Superscript Plus Sign", "⁺" },
    { "Superscript Minus", "⁻" },
    { "Superscript Equals Sign", "⁼" },
    { "Subscript Plus Sign", "₊" },
    { "Subscript Minus", "₋" },
    { "Subscript Equals Sign", "₌" },
    { "Script Capital P", "℘" },
    { "Double-Struck N-Ary Summation", "⅀" },
    { "Turned Sans-Serif Capital G", "⅁" },
    { "Turned Sans-Serif Capital L", "⅂" },
    { "Reversed Sans-Serif Capital L", "⅃" },
    { "Turned Sans-Serif Capital Y", "⅄" },
    { "Turned Ampersand", "⅋" },
    { "Leftwards Arrow", "←" },
    { "Upwards Arrow", "↑" },
    { "Rightwards Arrow", "→" },
    { "Downwards Arrow", "↓" },
    { "Left Right Arrow", "↔" },
    { "Leftwards Arrow with Stroke", "↚" },
    { "Rightwards Arrow with Stroke", "↛" },
    { "Rightwards Two Headed Arrow", "↠" },
    { "Rightwards Arrow with Tail", "↣" },
    { "Rightwards Arrow from Bar", "↦" },
    { "Left Right Arrow with Stroke", "↮" },
    { "Left Right Double Arrow with Stroke", "⇎" },
    { "Rightwards Double Arrow with Stroke", "⇏" },
    { "Rightwards Double Arrow", "⇒" },
    { "Left Right Double Arrow", "⇔" },
    { "Right Arrow with Small Circle", "⇴" },
    { "Downwards Arrow Leftwards of Upwards Arrow", "⇵" },
    { "Three Rightwards Arrows", "⇶" },
    { "Leftwards Arrow with Vertical Stroke", "⇷" },
    { "Rightwards Arrow with Vertical Stroke", "⇸" },
    { "Left Right Arrow with Vertical Stroke", "⇹" },
    { "Leftwards Arrow with Double Vertical Stroke", "⇺" },
    { "Rightwards Arrow with Double Vertical Stroke", "⇻" },
    { "Left Right Arrow with Double Vertical Stroke", "⇼" },
    { "Leftwards Open-Headed Arrow", "⇽" },
    { "Rightwards Open-Headed Arrow", "⇾" },
    { "Left Right Open-Headed Arrow", "⇿" },
    { "For All", "∀" },
    { "Complement", "∁" },
    { "Partial Differential", "∂" },
    { "There Exists", "∃" },
    { "There Does Not Exist", "∄" },
    { "Empty Set", "∅" },
    { "Increment", "∆" },
    { "Nabla", "∇" },
    { "Element Of", "∈" },
    { "Not An Element Of", "∉" },
    { "Small Element Of", "∊" },
    { "Contains as Member", "∋" },
    { "Does Not Contain as Member", "∌" },
    { "Small Contains as Member", "∍" },
    { "End of Proof", "∎" },
    { "N-Ary Product", "∏" },
    { "N-Ary Coproduct", "∐" },
    { "N-Ary Summation", "∑" },
    { "Minus Sign", "−" },
    { "Minus-or-Plus Sign", "∓" },
    { "Dot Plus", "∔" },
    { "Division Slash", "∕" },
    { "Set Minus", "∖" },
    { "Asterisk Operator", "∗" },
    { "Ring Operator", "∘" },
    { "Bullet Operator", "∙" },
    { "Square Root", "√" },
    { "Cube Root", "∛" },
    { "Fourth Root", "∜" },
    { "Proportional To", "∝" },
    { "Infinity", "∞" },
    { "Right Angle", "∟" },
    { "Angle", "∠" },
    { "Measured Angle", "∡" },
    { "Spherical Angle", "∢" },
    { "Divides", "∣" },
    { "Does Not Divide", "∤" },
    { "Parallel To", "∥" },
    { "Not Parallel To", "∦" },
    { "Logical And", "∧" },
    { "Logical Or", "∨" },
    { "Intersection", "∩" },
    { "Union", "∪" },
    { "Integral", "∫" },
    { "Double Integral", "∬" },
    { "Triple Integral", "∭" },
    { "Contour Integral", "∮" },
    { "Surface Integral", "∯" },
    { "Volume Integral", "∰" },
    { "Clockwise Integral", "∱" },
    { "Clockwise Contour Integral", "∲" },
    { "Anticlockwise Contour Integral", "∳" },
    { "Therefore", "∴" },
    { "Because", "∵" },
    { "Ratio", "∶" },
    { "Proportion", "∷" },
    { "Dot Minus", "∸" },
    { "Excess", "∹" },
    { "Geometric Proportion", "∺" },
    { "Homothetic", "∻" },
    { "Tilde Operator", "∼" },
    { "Reversed Tilde", "∽" },
    { "Inverted Lazy S", "∾" },
    { "Sine Wave", "∿" },
    { "Wreath Product", "≀" },
    { "Not Tilde", "≁" },
    { "Minus Tilde", "≂" },
    { "Asymptotically Equal To", "≃" },
    { "Not Asymptotically Equal To", "≄" },
    { "Approximately Equal To", "≅" },
    { "Approximately But Not Actually Equal To", "≆" },
    { "Neither Approximately Nor Actually Equal To", "≇" },
    { "Almost Equal To", "≈" },
    { "Not Almost Equal To", "≉" },
    { "Almost Equal or Equal To", "≊" },
    { "Triple Tilde", "≋" },
    { "All Equal To", "≌" },
    { "Equivalent To", "≍" },
    { "Geometrically Equivalent To", "≎" },
    { "Difference Between", "≏" },
    { "Approaches the Limit", "≐" },
    { "Geometrically Equal To", "≑" },
    { "Approximately Equal to or the Image Of", "≒" },
    { "Image of or Approximately Equal To", "≓" },
    { "Colon Equals", "≔" },
    { "Equals Colon", "≕" },
    { "Ring In Equal To", "≖" },
    { "Ring Equal To", "≗" },
    { "Corresponds To", "≘" },
    { "Estimates", "≙" },
    { "Equiangular To", "≚" },
    { "Star Equals", "≛" },
    { "Delta Equal To", "≜" },
    { "Equal to By Definition", "≝" },
    { "Measured By", "≞" },
    { "Questioned Equal To", "≟" },
    { "Not Equal To", "≠" },
    { "Identical To", "≡" },
    { "Not Identical To", "≢" },
    { "Strictly Equivalent To", "≣" },
    { "Less-Than or Equal To", "≤" },
    { "Greater-Than or Equal To", "≥" },
    { "Less-Than Over Equal To", "≦" },
    { "Greater-Than Over Equal To", "≧" },
    { "Less-Than But Not Equal To", "≨" },
    { "Greater-Than But Not Equal To", "≩" },
    { "Much Less-Than", "≪" },
    { "Much Greater-Than", "≫" },
    { "Between", "≬" },
    { "Not Equivalent To", "≭" },
    { "Not Less-Than", "≮" },
    { "Not Greater-Than", "≯" },
    { "Neither Less-Than Nor Equal To", "≰" },
    { "Neither Greater-Than Nor Equal To", "≱" },
    { "Less-Than or Equivalent To", "≲" },
    { "Greater-Than or Equivalent To", "≳" },
    { "Neither Less-Than Nor Equivalent To", "≴" },
    { "Neither Greater-Than Nor Equivalent To", "≵" },
    { "Less-Than or Greater-Than", "≶" },
    { "Greater-Than or Less-Than", "≷" },
    { "Neither Less-Than Nor Greater-Than", "≸" },
    { "Neither Greater-Than Nor Less-Than", "≹" },
    { "Precedes", "≺" },
    { "Succeeds", "≻" },
    { "Precedes or Equal To", "≼" },
    { "Succeeds or Equal To", "≽" },
    { "Precedes or Equivalent To", "≾" },
    { "Succeeds or Equivalent To", "≿" },
    { "Does Not Precede", "⊀" },
    { "Does Not Succeed", "⊁" },
    { "Subset Of", "⊂" },
    { "Superset Of", "⊃" },
    { "Not A Subset Of", "⊄" },
    { "Not A Superset Of", "⊅" },
    { "Subset of or Equal To", "⊆" },
    { "Superset of or Equal To", "⊇" },
    { "Neither A Subset of Nor Equal To", "⊈" },
    { "Neither A Superset of Nor Equal To", "⊉" },
    { "Subset of with Not Equal To", "⊊" },
    { "Superset of with Not Equal To", "⊋" },
    { "Multiset", "⊌" },
    { "Multiset Multiplication", "⊍" },
    { "Multiset Union", "⊎" },
    { "Square Image Of", "⊏" },
    { "Square Original Of", "⊐" },
    { "Square Image of or Equal To", "⊑" },
    { "Square Original of or Equal To", "⊒" },
    { "Square Cap", "⊓" },
    { "Square Cup", "⊔" },
    { "Circled Plus", "⊕" },
    { "Circled Minus", "⊖" },
    { "Circled Times", "⊗" },
    { "Circled Division Slash", "⊘" },
    { "Circled Dot Operator", "⊙" },
    { "Circled Ring Operator", "⊚" },
    { "Circled Asterisk Operator", "⊛" },
    { "Circled Equals", "⊜" },
    { "Circled Dash", "⊝" },
    { "Squared Plus", "⊞" },
    { "Squared Minus", "⊟" },
    { "Squared Times", "⊠" },
    { "Squared Dot Operator", "⊡" },
    { "Right Tack", "⊢" },
    { "Left Tack", "⊣" },
    { "Down Tack", "⊤" },
    { "Up Tack", "⊥" },
    { "Assertion", "⊦" },
    { "Models", "⊧" },
    { "True", "⊨" },
    { "Forces", "⊩" },
    { "Triple Vertical Bar Right Turnstile", "⊪" },
    { "Double Vertical Bar Double Right Turnstile", "⊫" },
    { "Does Not Prove", "⊬" },
    { "Not True", "⊭" },
    { "Does Not Force", "⊮" },
    { "Negated Double Vertical Bar Double Right Turnstile", "⊯" },
    { "Precedes Under Relation", "⊰" },
    { "Succeeds Under Relation", "⊱" },
    { "Normal Subgroup Of", "⊲" },
    { "Contains as Normal Subgroup", "⊳" },
    { "Normal Subgroup of or Equal To", "⊴" },
    { "Contains as Normal Subgroup or Equal To", "⊵" },
    { "Original Of", "⊶" },
    { "Image Of", "⊷" },
    { "Multimap", "⊸" },
    { "Hermitian Conjugate Matrix", "⊹" },
    { "Intercalate", "⊺" },
    { "Xor", "⊻" },
    { "Nand", "⊼" },
    { "Nor", "⊽" },
    { "Right Angle with Arc", "⊾" },
    { "Right Triangle", "⊿" },
    { "N-Ary Logical And", "⋀" },
    { "N-Ary Logical Or", "⋁" },
    { "N-Ary Intersection", "⋂" },
    { "N-Ary Union", "⋃" },
    { "Diamond Operator", "⋄" },
    { "Dot Operator", "⋅" },
    { "Star Operator", "⋆" },
    { "Division Times", "⋇" },
    { "Bowtie", "⋈" },
    { "Left Normal Factor Semidirect Product", "⋉" },
    { "Right Normal Factor Semidirect Product", "⋊" },
    { "Left Semidirect Product", "⋋" },
    { "Right Semidirect Product", "⋌" },
    { "Reversed Tilde Equals", "⋍" },
    { "Curly Logical Or", "⋎" },
    { "Curly Logical And", "⋏" },
    { "Double Subset", "⋐" },
    { "Double Superset", "⋑" },
    { "Double Intersection", "⋒" },
    { "Double Union", "⋓" },
    { "Pitchfork", "⋔" },
    { "Equal and Parallel To", "⋕" },
    { "Less-Than with Dot", "⋖" },
    { "Greater-Than with Dot", "⋗" },
    { "Very Much Less-Than", "⋘" },
    { "Very Much Greater-Than", "⋙" },
    { "Less-Than Equal to or Greater-Than", "⋚" },
    { "Greater-Than Equal to or Less-Than", "⋛" },
    { "Equal to or Less-Than", "⋜" },
    { "Equal to or Greater-Than", "⋝" },
    { "Equal to or Precedes", "⋞" },
    { "Equal to or Succeeds", "⋟" },
    { "Does Not Precede or Equal", "⋠" },
    { "Does Not Succeed or Equal", "⋡" },
    { "Not Square Image of or Equal To", "⋢" },
    { "Not Square Original of or Equal To", "⋣" },
    { "Square Image of or Not Equal To", "⋤" },
    { "Square Original of or Not Equal To", "⋥" },
    { "Less-Than But Not Equivalent To", "⋦" },
    { "Greater-Than But Not Equivalent To", "⋧" },
    { "Precedes But Not Equivalent To", "⋨" },
    { "Succeeds But Not Equivalent To", "⋩" },
    { "Not Normal Subgroup Of", "⋪" },
    { "Does Not Contain as Normal Subgroup", "⋫" },
    { "Not Normal Subgroup of or Equal To", "⋬" },
    { "Does Not Contain as Normal Subgroup or Equal", "⋭" },
    { "Vertical Ellipsis", "⋮" },
    { "Midline Horizontal Ellipsis", "⋯" },
    { "Up Right Diagonal Ellipsis", "⋰" },
    { "Down Right Diagonal Ellipsis", "⋱" },
    { "Element of with Long Horizontal Stroke", "⋲" },
    { "Element of with Vertical Bar at End of Horizontal Stroke", "⋳" },
    { "Small Element of with Vertical Bar at End of Horizontal Stroke", "⋴" },
    { "Element of with Dot Above", "⋵" },
    { "Element of with Overbar", "⋶" },
    { "Small Element of with Overbar", "⋷" },
    { "Element of with Underbar", "⋸" },
    { "Element of with Two Horizontal Strokes", "⋹" },
    { "Contains with Long Horizontal Stroke", "⋺" },
    { "Contains with Vertical Bar at End of Horizontal Stroke", "⋻" },
    { "Small Contains with Vertical Bar at End of Horizontal Stroke", "⋼" },
    { "Contains with Overbar", "⋽" },
    { "Small Contains with Overbar", "⋾" },
    { "Z Notation Bag Membership", "⋿" },
    { "Top Half Integral", "⌠" },
    { "Bottom Half Integral", "⌡" },
    { "Right Angle with Downwards Zigzag Arrow", "⍼" },
    { "Left Parenthesis Upper Hook", "⎛" },
    { "Left Parenthesis Extension", "⎜" },
    { "Left Parenthesis Lower Hook", "⎝" },
    { "Right Parenthesis Upper Hook", "⎞" },
    { "Right Parenthesis Extension", "⎟" },
    { "Right Parenthesis Lower Hook", "⎠" },
    { "Left Square Bracket Upper Corner", "⎡" },
    { "Left Square Bracket Extension", "⎢" },
    { "Left Square Bracket Lower Corner", "⎣" },
    { "Right Square Bracket Upper Corner", "⎤" },
    { "Right Square Bracket Extension", "⎥" },
    { "Right Square Bracket Lower Corner", "⎦" },
    { "Left Curly Bracket Upper Hook", "⎧" },
    { "Left Curly Bracket Middle Piece", "⎨" },
    { "Left Curly Bracket Lower Hook", "⎩" },
    { "Curly Bracket Extension", "⎪" },
    { "Right Curly Bracket Upper Hook", "⎫" },
    { "Right Curly Bracket Middle Piece", "⎬" },
    { "Right Curly Bracket Lower Hook", "⎭" },
    { "Integral Extension", "⎮" },
    { "Horizontal Line Extension", "⎯" },
    { "Upper Left or Lower Right Curly Bracket Section", "⎰" },
    { "Upper Right or Lower Left Curly Bracket Section", "⎱" },
    { "Summation Top", "⎲" },
    { "Summation Bottom", "⎳" },
    { "Top Parenthesis", "⏜" },
    { "Bottom Parenthesis", "⏝" },
    { "Top Curly Bracket", "⏞" },
    { "Bottom Curly Bracket", "⏟" },
    { "Top Tortoise Shell Bracket", "⏠" },
    { "Bottom Tortoise Shell Bracket", "⏡" },
    { "White Right-Pointing Triangle", "▷" },
    { "White Left-Pointing Triangle", "◁" },
    { "Upper Left Triangle", "◸" },
    { "Upper Right Triangle", "◹" },
    { "Lower Left Triangle", "◺" },
    { "White Medium Square", "◻" },
    { "Black Medium Square", "◼" },
    { "White Medium Small Square", "◽" },
    { "Black Medium Small Square", "◾" },
    { "Lower Right Triangle", "◿" },
    { "Music Sharp Sign", "♯" },
    { "Three Dimensional Angle", "⟀" },
    { "White Triangle Containing Small White Triangle", "⟁" },
    { "Perpendicular", "⟂" },
    { "Open Subset", "⟃" },
    { "Open Superset", "⟄" },
    { "or with Dot Inside", "⟇" },
    { "Reverse Solidus Preceding Subset", "⟈" },
    { "Superset Preceding Solidus", "⟉" },
    { "Vertical Bar with Horizontal Stroke", "⟊" },
    { "Mathematical Rising Diagonal", "⟋" },
    { "Long Division", "⟌" },
    { "Mathematical Falling Diagonal", "⟍" },
    { "Squared Logical And", "⟎" },
    { "Squared Logical Or", "⟏" },
    { "White Diamond with Centred Dot", "⟐" },
    { "and with Dot", "⟑" },
    { "Element of Opening Upwards", "⟒" },
    { "Lower Right Corner with Dot", "⟓" },
    { "Upper Left Corner with Dot", "⟔" },
    { "Left Outer Join", "⟕" },
    { "Right Outer Join", "⟖" },
    { "Full Outer Join", "⟗" },
    { "Large Up Tack", "⟘" },
    { "Large Down Tack", "⟙" },
    { "Left and Right Double Turnstile", "⟚" },
    { "Left and Right Tack", "⟛" },
    { "Left Multimap", "⟜" },
    { "Long Right Tack", "⟝" },
    { "Long Left Tack", "⟞" },
    { "Up Tack with Circle Above", "⟟" },
    { "Lozenge Divided By Horizontal Rule", "⟠" },
    { "White Concave-Sided Diamond", "⟡" },
    { "White Concave-Sided Diamond with Leftwards Tick", "⟢" },
    { "White Concave-Sided Diamond with Rightwards Tick", "⟣" },
    { "White Square with Leftwards Tick", "⟤" },
    { "White Square with Rightwards Tick", "⟥" },
    { "Upwards Quadruple Arrow", "⟰" },
    { "Downwards Quadruple Arrow", "⟱" },
    { "Anticlockwise Gapped Circle Arrow", "⟲" },
    { "Clockwise Gapped Circle Arrow", "⟳" },
    { "Right Arrow with Circled Plus", "⟴" },
    { "Long Leftwards Arrow", "⟵" },
    { "Long Rightwards Arrow", "⟶" },
    { "Long Left Right Arrow", "⟷" },
    { "Long Leftwards Double Arrow", "⟸" },
    { "Long Rightwards Double Arrow", "⟹" },
    { "Long Left Right Double Arrow", "⟺" },
    { "Long Leftwards Arrow from Bar", "⟻" },
    { "Long Rightwards Arrow from Bar", "⟼" },
    { "Long Leftwards Double Arrow from Bar", "⟽" },
    { "Long Rightwards Double Arrow from Bar", "⟾" },
    { "Long Rightwards Squiggle Arrow", "⟿" },
    { "Rightwards Two-Headed Arrow with Vertical Stroke", "⤀" },
    { "Rightwards Two-Headed Arrow with Double Vertical Stroke", "⤁" },
    { "Leftwards Double Arrow with Vertical Stroke", "⤂" },
    { "Rightwards Double Arrow with Vertical Stroke", "⤃" },
    { "Left Right Double Arrow with Vertical Stroke", "⤄" },
    { "Rightwards Two-Headed Arrow from Bar", "⤅" },
    { "Leftwards Double Arrow from Bar", "⤆" },
    { "Rightwards Double Arrow from Bar", "⤇" },
    { "Downwards Arrow with Horizontal Stroke", "⤈" },
    { "Upwards Arrow with Horizontal Stroke", "⤉" },
    { "Upwards Triple Arrow", "⤊" },
    { "Downwards Triple Arrow", "⤋" },
    { "Leftwards Double Dash Arrow", "⤌" },
    { "Rightwards Double Dash Arrow", "⤍" },
    { "Leftwards Triple Dash Arrow", "⤎" },
    { "Rightwards Triple Dash Arrow", "⤏" },
    { "Rightwards Two-Headed Triple Dash Arrow", "⤐" },
    { "Rightwards Arrow with Dotted Stem", "⤑" },
    { "Upwards Arrow to Bar", "⤒" },
    { "Downwards Arrow to Bar", "⤓" },
    { "Rightwards Arrow with Tail with Vertical Stroke", "⤔" },
    { "Rightwards Arrow with Tail with Double Vertical Stroke", "⤕" },
    { "Rightwards Two-Headed Arrow with Tail", "⤖" },
    { "Rightwards Two-Headed Arrow with Tail with Vertical Stroke", "⤗" },
    { "Rightwards Two-Headed Arrow with Tail with Double Vertical Stroke", "⤘" },
    { "Leftwards Arrow-Tail", "⤙" },
    { "Rightwards Arrow-Tail", "⤚" },
    { "Leftwards Double Arrow-Tail", "⤛" },
    { "Rightwards Double Arrow-Tail", "⤜" },
    { "Leftwards Arrow to Black Diamond", "⤝" },
    { "Rightwards Arrow to Black Diamond", "⤞" },
    { "Leftwards Arrow from Bar to Black Diamond", "⤟" },
    { "Rightwards Arrow from Bar to Black Diamond", "⤠" },
    { "North West and South East Arrow", "⤡" },
    { "North East and South West Arrow", "⤢" },
    { "North West Arrow with Hook", "⤣" },
    { "North East Arrow with Hook", "⤤" },
    { "South East Arrow with Hook", "⤥" },
    { "South West Arrow with Hook", "⤦" },
    { "North West Arrow and North East Arrow", "⤧" },
    { "North East Arrow and South East Arrow", "⤨" },
    { "South East Arrow and South West Arrow", "⤩" },
    { "South West Arrow and North West Arrow", "⤪" },
    { "Rising Diagonal Crossing Falling Diagonal", "⤫" },
    { "Falling Diagonal Crossing Rising Diagonal", "⤬" },
    { "South East Arrow Crossing North East Arrow", "⤭" },
    { "North East Arrow Crossing South East Arrow", "⤮" },
    { "Falling Diagonal Crossing North East Arrow", "⤯" },
    { "Rising Diagonal Crossing South East Arrow", "⤰" },
    { "North East Arrow Crossing North West Arrow", "⤱" },
    { "North West Arrow Crossing North East Arrow", "⤲" },
    { "Wave Arrow Pointing Directly Right", "⤳" },
    { "Arrow Pointing Rightwards Then Curving Upwards", "⤴" },
    { "Arrow Pointing Rightwards Then Curving Downwards", "⤵" },
    { "Arrow Pointing Downwards Then Curving Leftwards", "⤶" },
    { "Arrow Pointing Downwards Then Curving Rightwards", "⤷" },
    { "Right-Side Arc Clockwise Arrow", "⤸" },
    { "Left-Side Arc Anticlockwise Arrow", "⤹" },
    { "Top Arc Anticlockwise Arrow", "⤺" },
    { "Bottom Arc Anticlockwise Arrow", "⤻" },
    { "Top Arc Clockwise Arrow with Minus", "⤼" },
    { "Top Arc Anticlockwise Arrow with Plus", "⤽" },
    { "Lower Right Semicircular Clockwise Arrow", "⤾" },
    { "Lower Left Semicircular Anticlockwise Arrow", "⤿" },
    { "Anticlockwise Closed Circle Arrow", "⥀" },
    { "Clockwise Closed Circle Arrow", "⥁" },
    { "Rightwards Arrow Above Short Leftwards Arrow", "⥂" },
    { "Leftwards Arrow Above Short Rightwards Arrow", "⥃" },
    { "Short Rightwards Arrow Above Leftwards Arrow", "⥄" },
    { "Rightwards Arrow with Plus Below", "⥅" },
    { "Leftwards Arrow with Plus Below", "⥆" },
    { "Rightwards Arrow Through X", "⥇" },
    { "Left Right Arrow Through Small Circle", "⥈" },
    { "Upwards Two-Headed Arrow from Small Circle", "⥉" },
    { "Left Barb Up Right Barb Down Harpoon", "⥊" },
    { "Left Barb Down Right Barb Up Harpoon", "⥋" },
    { "Up Barb Right Down Barb Left Harpoon", "⥌" },
    { "Up Barb Left Down Barb Right Harpoon", "⥍" },
    { "Left Barb Up Right Barb Up Harpoon", "⥎" },
    { "Up Barb Right Down Barb Right Harpoon", "⥏" },
    { "Left Barb Down Right Barb Down Harpoon", "⥐" },
    { "Up Barb Left Down Barb Left Harpoon", "⥑" },
    { "Leftwards Harpoon with Barb Up to Bar", "⥒" },
    { "Rightwards Harpoon with Barb Up to Bar", "⥓" },
    { "Upwards Harpoon with Barb Right to Bar", "⥔" },
    { "Downwards Harpoon with Barb Right to Bar", "⥕" },
    { "Leftwards Harpoon with Barb Down to Bar", "⥖" },
    { "Rightwards Harpoon with Barb Down to Bar", "⥗" },
    { "Upwards Harpoon with Barb Left to Bar", "⥘" },
    { "Downwards Harpoon with Barb Left to Bar", "⥙" },
    { "Leftwards Harpoon with Barb Up from Bar", "⥚" },
    { "Rightwards Harpoon with Barb Up from Bar", "⥛" },
    { "Upwards Harpoon with Barb Right from Bar", "⥜" },
    { "Downwards Harpoon with Barb Right from Bar", "⥝" },
    { "Leftwards Harpoon with Barb Down from Bar", "⥞" },
    { "Rightwards Harpoon with Barb Down from Bar", "⥟" },
    { "Upwards Harpoon with Barb Left from Bar", "⥠" },
    { "Downwards Harpoon with Barb Left from Bar", "⥡" },
    { "Leftwards Harpoon with Barb Up Above Leftwards Harpoon with Barb Down", "⥢" },
    { "Upwards Harpoon with Barb Left Beside Upwards Harpoon with Barb Right", "⥣" },
    { "Rightwards Harpoon with Barb Up Above Rightwards Harpoon with Barb Down", "⥤" },
    { "Downwards Harpoon with Barb Left Beside Downwards Harpoon with Barb Right", "⥥" },
    { "Leftwards Harpoon with Barb Up Above Rightwards Harpoon with Barb Up", "⥦" },
    { "Leftwards Harpoon with Barb Down Above Rightwards Harpoon with Barb Down", "⥧" },
    { "Rightwards Harpoon with Barb Up Above Leftwards Harpoon with Barb Up", "⥨" },
    { "Rightwards Harpoon with Barb Down Above Leftwards Harpoon with Barb Down", "⥩" },
    { "Leftwards Harpoon with Barb Up Above Long Dash", "⥪" },
    { "Leftwards Harpoon with Barb Down Below Long Dash", "⥫" },
    { "Rightwards Harpoon with Barb Up Above Long Dash", "⥬" },
    { "Rightwards Harpoon with Barb Down Below Long Dash", "⥭" },
    { "Upwards Harpoon with Barb Left Beside Downwards Harpoon with Barb Right", "⥮" },
    { "Downwards Harpoon with Barb Left Beside Upwards Harpoon with Barb Right", "⥯" },
    { "Right Double Arrow with Rounded Head", "⥰" },
    { "Equals Sign Above Rightwards Arrow", "⥱" },
    { "Tilde Operator Above Rightwards Arrow", "⥲" },
    { "Leftwards Arrow Above Tilde Operator", "⥳" },
    { "Rightwards Arrow Above Tilde Operator", "⥴" },
    { "Rightwards Arrow Above Almost Equal To", "⥵" },
    { "Less-Than Above Leftwards Arrow", "⥶" },
    { "Leftwards Arrow Through Less-Than", "⥷" },
    { "Greater-Than Above Rightwards Arrow", "⥸" },
    { "Subset Above Rightwards Arrow", "⥹" },
    { "Leftwards Arrow Through Subset", "⥺" },
    { "Superset Above Leftwards Arrow", "⥻" },
    { "Left Fish Tail", "⥼" },
    { "Right Fish Tail", "⥽" },
    { "Up Fish Tail", "⥾" },
    { "Down Fish Tail", "⥿" },
    { "Triple Vertical Bar Delimiter", "⦀" },
    { "Z Notation Spot", "⦁" },
    { "Z Notation Type Colon", "⦂" },
    { "Dotted Fence", "⦙" },
    { "Vertical Zigzag Line", "⦚" },
    { "Measured Angle Opening Left", "⦛" },
    { "Right Angle Variant with Square", "⦜" },
    { "Measured Right Angle with Dot", "⦝" },
    { "Angle with S Inside", "⦞" },
    { "Acute Angle", "⦟" },
    { "Spherical Angle Opening Left", "⦠" },
    { "Spherical Angle Opening Up", "⦡" },
    { "Turned Angle", "⦢" },
    { "Reversed Angle", "⦣" },
    { "Angle with Underbar", "⦤" },
    { "Reversed Angle with Underbar", "⦥" },
    { "Oblique Angle Opening Up", "⦦" },
    { "Oblique Angle Opening Down", "⦧" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Up and Right", "⦨" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Up and Left", "⦩" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Down and Right", "⦪" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Down and Left", "⦫" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Right and Up", "⦬" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Left and Up", "⦭" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Right and Down", "⦮" },
    { "Measured Angle with Open Arm Ending In Arrow Pointing Left and Down", "⦯" },
    { "Reversed Empty Set", "⦰" },
    { "Empty Set with Overbar", "⦱" },
    { "Empty Set with Small Circle Above", "⦲" },
    { "Empty Set with Right Arrow Above", "⦳" },
    { "Empty Set with Left Arrow Above", "⦴" },
    { "Circle with Horizontal Bar", "⦵" },
    { "Circled Vertical Bar", "⦶" },
    { "Circled Parallel", "⦷" },
    { "Circled Reverse Solidus", "⦸" },
    { "Circled Perpendicular", "⦹" },
    { "Circle Divided By Horizontal Bar and Top Half Divided By Vertical Bar", "⦺" },
    { "Circle with Superimposed X", "⦻" },
    { "Circled Anticlockwise-Rotated Division Sign", "⦼" },
    { "Up Arrow Through Circle", "⦽" },
    { "Circled White Bullet", "⦾" },
    { "Circled Bullet", "⦿" },
    { "Circled Less-Than", "⧀" },
    { "Circled Greater-Than", "⧁" },
    { "Circle with Small Circle to the Right", "⧂" },
    { "Circle with Two Horizontal Strokes to the Right", "⧃" },
    { "Squared Rising Diagonal Slash", "⧄" },
    { "Squared Falling Diagonal Slash", "⧅" },
    { "Squared Asterisk", "⧆" },
    { "Squared Small Circle", "⧇" },
    { "Squared Square", "⧈" },
    { "Two Joined Squares", "⧉" },
    { "Triangle with Dot Above", "⧊" },
    { "Triangle with Underbar", "⧋" },
    { "S In Triangle", "⧌" },
    { "Triangle with Serifs at Bottom", "⧍" },
    { "Right Triangle Above Left Triangle", "⧎" },
    { "Left Triangle Beside Vertical Bar", "⧏" },
    { "Vertical Bar Beside Right Triangle", "⧐" },
    { "Bowtie with Left Half Black", "⧑" },
    { "Bowtie with Right Half Black", "⧒" },
    { "Black Bowtie", "⧓" },
    { "Times with Left Half Black", "⧔" },
    { "Times with Right Half Black", "⧕" },
    { "White Hourglass", "⧖" },
    { "Black Hourglass", "⧗" },
    { "Incomplete Infinity", "⧜" },
    { "Tie Over Infinity", "⧝" },
    { "Infinity Negated with Vertical Bar", "⧞" },
    { "Double-Ended Multimap", "⧟" },
    { "Square with Contoured Outline", "⧠" },
    { "Increases As", "⧡" },
    { "Shuffle Product", "⧢" },
    { "Equals Sign and Slanted Parallel", "⧣" },
    { "Equals Sign and Slanted Parallel with Tilde Above", "⧤" },
    { "Identical to and Slanted Parallel", "⧥" },
    { "Gleich Stark", "⧦" },
    { "Thermodynamic", "⧧" },
    { "Down-Pointing Triangle with Left Half Black", "⧨" },
    { "Down-Pointing Triangle with Right Half Black", "⧩" },
    { "Black Diamond with Down Arrow", "⧪" },
    { "Black Lozenge", "⧫" },
    { "White Circle with Down Arrow", "⧬" },
    { "Black Circle with Down Arrow", "⧭" },
    { "Error-Barred White Square", "⧮" },
    { "Error-Barred Black Square", "⧯" },
    { "Error-Barred White Diamond", "⧰" },
    { "Error-Barred Black Diamond", "⧱" },
    { "Error-Barred White Circle", "⧲" },
    { "Error-Barred Black Circle", "⧳" },
    { "Rule-Delayed", "⧴" },
    { "Reverse Solidus Operator", "⧵" },
    { "Solidus with Overbar", "⧶" },
    { "Reverse Solidus with Horizontal Stroke", "⧷" },
    { "Big Solidus", "⧸" },
    { "Big Reverse Solidus", "⧹" },
    { "Double Plus", "⧺" },
    { "Triple Plus", "⧻" },
    { "Tiny", "⧾" },
    { "Miny", "⧿" },
    { "N-Ary Circled Dot Operator", "⨀" },
    { "N-Ary Circled Plus Operator", "⨁" },
    { "N-Ary Circled Times Operator", "⨂" },
    { "N-Ary Union Operator with Dot", "⨃" },
    { "N-Ary Union Operator with Plus", "⨄" },
    { "N-Ary Square Intersection Operator", "⨅" },
    { "N-Ary Square Union Operator", "⨆" },
    { "Two Logical and Operator", "⨇" },
    { "Two Logical or Operator", "⨈" },
    { "N-Ary Times Operator", "⨉" },
    { "Modulo Two Sum", "⨊" },
    { "Summation with Integral", "⨋" },
    { "Quadruple Integral Operator", "⨌" },
    { "Finite Part Integral", "⨍" },
    { "Integral with Double Stroke", "⨎" },
    { "Integral Average with Slash", "⨏" },
    { "Circulation Function", "⨐" },
    { "Anticlockwise Integration", "⨑" },
    { "Line Integration with Rectangular Path Around Pole", "⨒" },
    { "Line Integration with Semicircular Path Around Pole", "⨓" },
    { "Line Integration Not Including the Pole", "⨔" },
    { "Integral Around A Point Operator", "⨕" },
    { "Quaternion Integral Operator", "⨖" },
    { "Integral with Leftwards Arrow with Hook", "⨗" },
    { "Integral with Times Sign", "⨘" },
    { "Integral with Intersection", "⨙" },
    { "Integral with Union", "⨚" },
    { "Integral with Overbar", "⨛" },
    { "Integral with Underbar", "⨜" },
    { "Join", "⨝" },
    { "Large Left Triangle Operator", "⨞" },
    { "Z Notation Schema Composition", "⨟" },
    { "Z Notation Schema Piping", "⨠" },
    { "Z Notation Schema Projection", "⨡" },
    { "Plus Sign with Small Circle Above", "⨢" },
    { "Plus Sign with Circumflex Accent Above", "⨣" },
    { "Plus Sign with Tilde Above", "⨤" },
    { "Plus Sign with Dot Below", "⨥" },
    { "Plus Sign with Tilde Below", "⨦" },
    { "Plus Sign with Subscript Two", "⨧" },
    { "Plus Sign with Black Triangle", "⨨" },
    { "Minus Sign with Comma Above", "⨩" },
    { "Minus Sign with Dot Below", "⨪" },
    { "Minus Sign with Falling Dots", "⨫" },
    { "Minus Sign with Rising Dots", "⨬" },
    { "Plus Sign In Left Half Circle", "⨭" },
    { "Plus Sign In Right Half Circle", "⨮" },
    { "Vector or Cross Product", "⨯" },
    { "Multiplication Sign with Dot Above", "⨰" },
    { "Multiplication Sign with Underbar", "⨱" },
    { "Semidirect Product with Bottom Closed", "⨲" },
    { "Smash Product", "⨳" },
    { "Multiplication Sign In Left Half Circle", "⨴" },
    { "Multiplication Sign In Right Half Circle", "⨵" },
    { "Circled Multiplication Sign with Circumflex Accent", "⨶" },
    { "Multiplication Sign In Double Circle", "⨷" },
    { "Circled Division Sign", "⨸" },
    { "Plus Sign In Triangle", "⨹" },
    { "Minus Sign In Triangle", "⨺" },
    { "Multiplication Sign In Triangle", "⨻" },
    { "Interior Product", "⨼" },
    { "Righthand Interior Product", "⨽" },
    { "Z Notation Relational Composition", "⨾" },
    { "Amalgamation or Coproduct", "⨿" },
    { "Intersection with Dot", "⩀" },
    { "Union with Minus Sign", "⩁" },
    { "Union with Overbar", "⩂" },
    { "Intersection with Overbar", "⩃" },
    { "Intersection with Logical And", "⩄" },
    { "Union with Logical Or", "⩅" },
    { "Union Above Intersection", "⩆" },
    { "Intersection Above Union", "⩇" },
    { "Union Above Bar Above Intersection", "⩈" },
    { "Intersection Above Bar Above Union", "⩉" },
    { "Union Beside and Joined with Union", "⩊" },
    { "Intersection Beside and Joined with Intersection", "⩋" },
    { "Closed Union with Serifs", "⩌" },
    { "Closed Intersection with Serifs", "⩍" },
    { "Double Square Intersection", "⩎" },
    { "Double Square Union", "⩏" },
    { "Closed Union with Serifs and Smash Product", "⩐" },
    { "Logical and with Dot Above", "⩑" },
    { "Logical or with Dot Above", "⩒" },
    { "Double Logical And", "⩓" },
    { "Double Logical Or", "⩔" },
    { "Two Intersecting Logical And", "⩕" },
    { "Two Intersecting Logical Or", "⩖" },
    { "Sloping Large Or", "⩗" },
    { "Sloping Large And", "⩘" },
    { "Logical or Overlapping Logical And", "⩙" },
    { "Logical and with Middle Stem", "⩚" },
    { "Logical or with Middle Stem", "⩛" },
    { "Logical and with Horizontal Dash", "⩜" },
    { "Logical or with Horizontal Dash", "⩝" },
    { "Logical and with Double Overbar", "⩞" },
    { "Logical and with Underbar", "⩟" },
    { "Logical and with Double Underbar", "⩠" },
    { "Small Vee with Underbar", "⩡" },
    { "Logical or with Double Overbar", "⩢" },
    { "Logical or with Double Underbar", "⩣" },
    { "Z Notation Domain Antirestriction", "⩤" },
    { "Z Notation Range Antirestriction", "⩥" },
    { "Equals Sign with Dot Below", "⩦" },
    { "Identical with Dot Above", "⩧" },
    { "Triple Horizontal Bar with Double Vertical Stroke", "⩨" },
    { "Triple Horizontal Bar with Triple Vertical Stroke", "⩩" },
    { "Tilde Operator with Dot Above", "⩪" },
    { "Tilde Operator with Rising Dots", "⩫" },
    { "Similar Minus Similar", "⩬" },
    { "Congruent with Dot Above", "⩭" },
    { "Equals with Asterisk", "⩮" },
    { "Almost Equal to with Circumflex Accent", "⩯" },
    { "Approximately Equal or Equal To", "⩰" },
    { "Equals Sign Above Plus Sign", "⩱" },
    { "Plus Sign Above Equals Sign", "⩲" },
    { "Equals Sign Above Tilde Operator", "⩳" },
    { "Double Colon Equal", "⩴" },
    { "Two Consecutive Equals Signs", "⩵" },
    { "Three Consecutive Equals Signs", "⩶" },
    { "Equals Sign with Two Dots Above and Two Dots Below", "⩷" },
    { "Equivalent with Four Dots Above", "⩸" },
    { "Less-Than with Circle Inside", "⩹" },
    { "Greater-Than with Circle Inside", "⩺" },
    { "Less-Than with Question Mark Above", "⩻" },
    { "Greater-Than with Question Mark Above", "⩼" },
    { "Less-Than or Slanted Equal To", "⩽" },
    { "Greater-Than or Slanted Equal To", "⩾" },
    { "Less-Than or Slanted Equal to with Dot Inside", "⩿" },
    { "Greater-Than or Slanted Equal to with Dot Inside", "⪀" },
    { "Less-Than or Slanted Equal to with Dot Above", "⪁" },
    { "Greater-Than or Slanted Equal to with Dot Above", "⪂" },
    { "Less-Than or Slanted Equal to with Dot Above Right", "⪃" },
    { "Greater-Than or Slanted Equal to with Dot Above Left", "⪄" },
    { "Less-Than or Approximate", "⪅" },
    { "Greater-Than or Approximate", "⪆" },
    { "Less-Than and Single-Line Not Equal To", "⪇" },
    { "Greater-Than and Single-Line Not Equal To", "⪈" },
    { "Less-Than and Not Approximate", "⪉" },
    { "Greater-Than and Not Approximate", "⪊" },
    { "Less-Than Above Double-Line Equal Above Greater-Than", "⪋" },
    { "Greater-Than Above Double-Line Equal Above Less-Than", "⪌" },
    { "Less-Than Above Similar or Equal", "⪍" },
    { "Greater-Than Above Similar or Equal", "⪎" },
    { "Less-Than Above Similar Above Greater-Than", "⪏" },
    { "Greater-Than Above Similar Above Less-Than", "⪐" },
    { "Less-Than Above Greater-Than Above Double-Line Equal", "⪑" },
    { "Greater-Than Above Less-Than Above Double-Line Equal", "⪒" },
    { "Less-Than Above Slanted Equal Above Greater-Than Above Slanted Equal", "⪓" },
    { "Greater-Than Above Slanted Equal Above Less-Than Above Slanted Equal", "⪔" },
    { "Slanted Equal to or Less-Than", "⪕" },
    { "Slanted Equal to or Greater-Than", "⪖" },
    { "Slanted Equal to or Less-Than with Dot Inside", "⪗" },
    { "Slanted Equal to or Greater-Than with Dot Inside", "⪘" },
    { "Double-Line Equal to or Less-Than", "⪙" },
    { "Double-Line Equal to or Greater-Than", "⪚" },
    { "Double-Line Slanted Equal to or Less-Than", "⪛" },
    { "Double-Line Slanted Equal to or Greater-Than", "⪜" },
    { "Similar or Less-Than", "⪝" },
    { "Similar or Greater-Than", "⪞" },
    { "Similar Above Less-Than Above Equals Sign", "⪟" },
    { "Similar Above Greater-Than Above Equals Sign", "⪠" },
    { "Double Nested Less-Than", "⪡" },
    { "Double Nested Greater-Than", "⪢" },
    { "Double Nested Less-Than with Underbar", "⪣" },
    { "Greater-Than Overlapping Less-Than", "⪤" },
    { "Greater-Than Beside Less-Than", "⪥" },
    { "Less-Than Closed By Curve", "⪦" },
    { "Greater-Than Closed By Curve", "⪧" },
    { "Less-Than Closed By Curve Above Slanted Equal", "⪨" },
    { "Greater-Than Closed By Curve Above Slanted Equal", "⪩" },
    { "Smaller Than", "⪪" },
    { "Larger Than", "⪫" },
    { "Smaller Than or Equal To", "⪬" },
    { "Larger Than or Equal To", "⪭" },
    { "Equals Sign with Bumpy Above", "⪮" },
    { "Precedes Above Single-Line Equals Sign", "⪯" },
    { "Succeeds Above Single-Line Equals Sign", "⪰" },
    { "Precedes Above Single-Line Not Equal To", "⪱" },
    { "Succeeds Above Single-Line Not Equal To", "⪲" },
    { "Precedes Above Equals Sign", "⪳" },
    { "Succeeds Above Equals Sign", "⪴" },
    { "Precedes Above Not Equal To", "⪵" },
    { "Succeeds Above Not Equal To", "⪶" },
    { "Precedes Above Almost Equal To", "⪷" },
    { "Succeeds Above Almost Equal To", "⪸" },
    { "Precedes Above Not Almost Equal To", "⪹" },
    { "Succeeds Above Not Almost Equal To", "⪺" },
    { "Double Precedes", "⪻" },
    { "Double Succeeds", "⪼" },
    { "Subset with Dot", "⪽" },
    { "Superset with Dot", "⪾" },
    { "Subset with Plus Sign Below", "⪿" },
    { "Superset with Plus Sign Below", "⫀" },
    { "Subset with Multiplication Sign Below", "⫁" },
    { "Superset with Multiplication Sign Below", "⫂" },
    { "Subset of or Equal to with Dot Above", "⫃" },
    { "Superset of or Equal to with Dot Above", "⫄" },
    { "Subset of Above Equals Sign", "⫅" },
    { "Superset of Above Equals Sign", "⫆" },
    { "Subset of Above Tilde Operator", "⫇" },
    { "Superset of Above Tilde Operator", "⫈" },
    { "Subset of Above Almost Equal To", "⫉" },
    { "Superset of Above Almost Equal To", "⫊" },
    { "Subset of Above Not Equal To", "⫋" },
    { "Superset of Above Not Equal To", "⫌" },
    { "Square Left Open Box Operator", "⫍" },
    { "Square Right Open Box Operator", "⫎" },
    { "Closed Subset", "⫏" },
    { "Closed Superset", "⫐" },
    { "Closed Subset or Equal To", "⫑" },
    { "Closed Superset or Equal To", "⫒" },
    { "Subset Above Superset", "⫓" },
    { "Superset Above Subset", "⫔" },
    { "Subset Above Subset", "⫕" },
    { "Superset Above Superset", "⫖" },
    { "Superset Beside Subset", "⫗" },
    { "Superset Beside and Joined By Dash with Subset", "⫘" },
    { "Element of Opening Downwards", "⫙" },
    { "Pitchfork with Tee Top", "⫚" },
    { "Transversal Intersection", "⫛" },
    { "Forking", "⫝̸" },
    { "Nonforking", "⫝" },
    { "Short Left Tack", "⫞" },
    { "Short Down Tack", "⫟" },
    { "Short Up Tack", "⫠" },
    { "Perpendicular with S", "⫡" },
    { "Vertical Bar Triple Right Turnstile", "⫢" },
    { "Double Vertical Bar Left Turnstile", "⫣" },
    { "Vertical Bar Double Left Turnstile", "⫤" },
    { "Double Vertical Bar Double Left Turnstile", "⫥" },
    { "Long Dash from Left Member of Double Vertical", "⫦" },
    { "Short Down Tack with Overbar", "⫧" },
    { "Short Up Tack with Underbar", "⫨" },
    { "Short Up Tack Above Short Down Tack", "⫩" },
    { "Double Down Tack", "⫪" },
    { "Double Up Tack", "⫫" },
    { "Double Stroke Not Sign", "⫬" },
    { "Reversed Double Stroke Not Sign", "⫭" },
    { "Does Not Divide with Reversed Negation Slash", "⫮" },
    { "Vertical Line with Circle Above", "⫯" },
    { "Vertical Line with Circle Below", "⫰" },
    { "Down Tack with Circle Below", "⫱" },
    { "Parallel with Horizontal Stroke", "⫲" },
    { "Parallel with Tilde Operator", "⫳" },
    { "Triple Vertical Bar Binary Relation", "⫴" },
    { "Triple Vertical Bar with Horizontal Stroke", "⫵" },
    { "Triple Colon Operator", "⫶" },
    { "Triple Nested Less-Than", "⫷" },
    { "Triple Nested Greater-Than", "⫸" },
    { "Double-Line Slanted Less-Than or Equal To", "⫹" },
    { "Double-Line Slanted Greater-Than or Equal To", "⫺" },
    { "Triple Solidus Binary Relation", "⫻" },
    { "Large Triple Vertical Bar Operator", "⫼" },
    { "Double Solidus Operator", "⫽" },
    { "White Vertical Bar", "⫾" },
    { "N-Ary White Vertical Bar", "⫿" },
    { "Left Arrow with Small Circle", "⬰" },
    { "Three Leftwards Arrows", "⬱" },
    { "Left Arrow with Circled Plus", "⬲" },
    { "Long Leftwards Squiggle Arrow", "⬳" },
    { "Leftwards Two-Headed Arrow with Vertical Stroke", "⬴" },
    { "Leftwards Two-Headed Arrow with Double Vertical Stroke", "⬵" },
    { "Leftwards Two-Headed Arrow from Bar", "⬶" },
    { "Leftwards Two-Headed Triple Dash Arrow", "⬷" },
    { "Leftwards Arrow with Dotted Stem", "⬸" },
    { "Leftwards Arrow with Tail with Vertical Stroke", "⬹" },
    { "Leftwards Arrow with Tail with Double Vertical Stroke", "⬺" },
    { "Leftwards Two-Headed Arrow with Tail", "⬻" },
    { "Leftwards Two-Headed Arrow with Tail with Vertical Stroke", "⬼" },
    { "Leftwards Two-Headed Arrow with Tail with Double Vertical Stroke", "⬽" },
    { "Leftwards Arrow Through X", "⬾" },
    { "Wave Arrow Pointing Directly Left", "⬿" },
    { "Equals Sign Above Leftwards Arrow", "⭀" },
    { "Reverse Tilde Operator Above Leftwards Arrow", "⭁" },
    { "Leftwards Arrow Above Reverse Almost Equal To", "⭂" },
    { "Rightwards Arrow Through Greater-Than", "⭃" },
    { "Rightwards Arrow Through Superset", "⭄" },
    { "Reverse Tilde Operator Above Rightwards Arrow", "⭇" },
    { "Rightwards Arrow Above Reverse Almost Equal To", "⭈" },
    { "Tilde Operator Above Leftwards Arrow", "⭉" },
    { "Leftwards Arrow Above Almost Equal To", "⭊" },
    { "Leftwards Arrow Above Reverse Tilde Operator", "⭋" },
    { "Rightwards Arrow Above Reverse Tilde Operator", "⭌" },
    { "Hebrew Letter Alternative Plus Sign", "﬩" },
    { "Small Plus Sign", "﹢" },
    { "Small Less-Than Sign", "﹤" },
    { "Small Greater-Than Sign", "﹥" },
    { "Small Equals Sign", "﹦" },
    { "Fullwidth Plus Sign", "＋" },
    { "Fullwidth Less-Than Sign", "＜" },
    { "Fullwidth Equals Sign", "＝" },
    { "Fullwidth Greater-Than Sign", "＞" },
    { "Fullwidth Vertical Line", "｜" },
    { "Fullwidth Tilde", "～" },
    { "Fullwidth Not Sign", "￢" },
    { "Halfwidth Leftwards Arrow", "￩" },
    { "Halfwidth Upwards Arrow", "￪" },
    { "Halfwidth Rightwards Arrow", "￫" },
    { "Halfwidth Downwards Arrow", "￬" },
    { "Mathematical Bold Nabla", "𝛁" },
    { "Mathematical Bold Partial Differential", "𝛛" },
    { "Mathematical Italic Nabla", "𝛻" },
    { "Mathematical Italic Partial Differential", "𝜕" },
    { "Mathematical Bold Italic Nabla", "𝜵" },
    { "Mathematical Bold Italic Partial Differential", "𝝏" },
    { "Mathematical Sans-Serif Bold Nabla", "𝝯" },
    { "Mathematical Sans-Serif Bold Partial Differential", "𝞉" },
    { "Mathematical Sans-Serif Bold Italic Nabla", "𝞩" },
    { "Mathematical Sans-Serif Bold Italic Partial Differential", "𝟃" },
    { "Arabic Mathematical Operator Meem with Hah with Tatweel", "𞻰" },
    { "Arabic Mathematical Operator Hah with Dal", "𞻱" },
    { "Natural numbers", "ℕ" },
}
